version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: wanderer-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - wanderer-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wanderer-backend
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt
    networks:
      - wanderer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wanderer-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - wanderer-network

networks:
  wanderer-network:
    driver: bridge