
version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  locator:
    build:
      context: .
      dockerfile: ./Dockerfile.locator
    container_name: locator
    depends_on:
      - mqtt
    volumes:
      - ./standart.beacons:/app/standart.beacons:ro
      - ./standart.path:/app/standart.path:rw
      - ./scripts/calibration.json:/app/calibration.json:ro
    restart: unless-stopped