services:
  # Основной сервер
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
    command: node server.js
    depends_on:
      - emqx
    restart: unless-stopped
    networks:
      - app-network

  # MQTT брокер EMQX
  emqx:
    image: emqx/emqx:5.4
    container_name: emqx
    ports:
      - "1883:1883" # порт
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "8081:18083"  
    environment:
      - EMQX_NODE_NAME=emqx@node
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge