services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      - "3277:3277"
    depends_on:
      - mosquitto

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
# services:
#   mosquitto:
#     image: eclipse-mosquitto:2.0
#     container_name: mosquitto
#     restart: unless-stopped
#     ports:
#       - "1883:1883"
#       - "9001:9001"
#     volumes:
#       - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
#       - ./data:/mosquitto/data
#       - ./log:/mosquitto/log
