services:
  mqtt:
    image: eclipse-mosquitto:2
    pull_policy: always
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./backend/app/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$$SYS/broker/version", "-C", "1", "-W", "3"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: indoor-backend
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: indoor-frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  mosquitto_data:
  mosquitto_log:
