FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY app/requirements.txt .
RUN pip install -r requirements.txt

\CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
